---
title: "Tidy Tuesday HIdden Gems"
author: "Tadeo Aviles Zuniga"
date: '2022-05-03'
output: 
 prettydoc::html_pretty:
    theme: architect
    highlight: github
---


### **Introduction** ###
**Data:** [TidyTuesday-Kaggle Hidden Gems](https://github.com/rfordatascience/tidytuesday/blob/master/data/2022/2022-04-26/readme.md)
 
```{r, message = FALSE, warning = FALSE, echo = FALSE}
#load data 
library(lubridate)
library(ggtext)
library(here)
library(tidyverse)
library(ggplot2)
library(DataExplorer)
library(ggthemes)
library(viridis)

```

```{r load, echo = FALSE, warning = FALSE, message = FALSE}
#Read in data
#load tidy tuesday data US solar and wind
hidden_gems <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-04-26/hidden_gems.csv')

```

```{r wrangle, echo = FALSE, warning = FALSE, message = FALSE}

hg<-hidden_gems  %>% filter(vol >= 90) %>% #Wrangle data by filtering most volumes of episodes 
select(vol,date,title,review,author_name) %>%  group_by(vol)#selecing columns and group by volume
```
**Plot:**
```{r plot , fig.width = 6, fig.height=7, fig.asp=1.2, fig.align='center', message = FALSE,echo = TRUE,  warning = FALSE}
hg %>% 
ggplot(aes(x=vol, y=title , group_by = vol)) +
geom_point(aes(color=vol), size=.5) +
geom_tile(height=.8, width=.8, color="black") +
  scale_fill_gradient()+
  theme_classic()+
  labs(title = "Titles with more than 90 Volumes", 
       x = "Volume",
       y = "Titles ")+
  theme( axis.text.y = element_text(color="black", size = 6),
         axis.text.x=element_text(color = "red"),#change axis title
plot.margin=margin(.5,.75,.5,.5, unit="cm"),# change margins 
strip.text = element_text(size=10.5, face="bold"),
title =element_text(size=11, color = "red"))#change color title 


```